name: myenv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h57dcf0c_0
  - brotli-python=1.0.9=py311h5da7b33_9
  - brotlicffi=1.0.9.2=py311h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - cffi=1.17.1=py311h827c3e9_1
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - expat=2.7.1=h8ddb27b_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9e=h827c3e9_3
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown=3.8=py311haa95532_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - numexpr=2.10.1=py311h4cd664f_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.16=h3f729d1_0
  - pip=25.1=pyhc872135_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pyqt=6.7.1=py311h5da7b33_1
  - pyqt6-sip=13.9.1=py311h827c3e9_1
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.11_cuda11.8_cudnn9_0
  - pytorch-cuda=11.8=h24eeafa_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py311haa95532_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - qtbase=6.7.3=h0804d20_0
  - qtdeclarative=6.7.3=h5da7b33_0
  - qtsvg=6.7.3=hf2fb9eb_0
  - qttools=6.7.3=h0de5f00_0
  - qtwebchannel=6.7.3=h5da7b33_0
  - qtwebsockets=6.7.3=h5da7b33_0
  - requests=2.32.4=py311haa95532_0
  - setuptools=78.1.1=py311haa95532_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h5e9d12e_1
  - tornado=6.5.1=py311h827c3e9_0
  - typing_extensions=4.12.2=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - easydict==1.13
      - filelock==3.18.0
      - filterpy==1.4.5
      - fonttools==4.58.5
      - fsspec==2025.5.1
      - groq==0.30.0
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - lap==0.5.12
      - matplotlib==3.10.3
      - natsort==8.4.0
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.1
      - pedpy==1.3.2
      - pillow==11.3.0
      - protobuf==6.31.1
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - scipy==1.16.0
      - shapely==2.1.1
      - sniffio==1.3.1
      - sympy==1.13.1
      - tensorboardx==2.6.4
      - torch==2.7.1
      - torchaudio==2.5.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - ultralytics==8.3.166
      - ultralytics-thop==2.0.14
